name: Publish
on:
  push:
    tags: [v*]
env:
  OPENRCT2_DIR: OpenRCT2
jobs:
  release:
    name: Release New Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Build Plugin
        run: yarn build

      - name: Obtain Current Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Generate Release Notes
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: true
          stripHeaders: true
          stripGeneratorNotice: true

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body_path: CHANGELOG.md

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/ride-themer.js
          asset_name: ride-themer-${{ steps.get_version.outputs.version }}.js
          asset_content_type: text/javascript

      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          stripGeneratorNotice: true

      - name: Commit Changelog
        run: |
          git config --local user.email actions@github.com
          git config --local user.name GitHub
          git add CHANGELOG.md
          git commit -am "Update CHANGELOG for Release ${{ steps.get_version.outputs.version }}"

      - name: Push Changelog Updates to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}